apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oizs76lfl-go
  janus-idp.io/tekton: oizs76lfl-go
  backstage.io/kubernetes-id: oizs76lfl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oizs76lfl-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
