apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oizs76lfl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oizs76lfl-go 
  name: oizs76lfl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oizs76lfl-go 
